apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafdrop
  namespace: default
  labels:
    app: kafdrop
spec:
  selector:
    matchLabels:
      app: kafdrop
  template:
    metadata:
      labels:
        app: kafdrop
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: zookeeper
          image: "obsidiandynamics/kafdrop"
          env:
            - name: JVM_OPTS
              value: "-Xms32M -Xmx64M"
            - name: SERVER_SERVLET_CONTEXTPATH
              value: "/"
            - name: KAFKA_BROKERCONNECT
              value: "kafka1.default:19092"
---
apiVersion: v1
kind: Service
metadata:
  name: kafdrop
  namespace: default
  labels:
    app: kafdrop
spec:
  type: ClusterIP
  ports:
  - name: client
    port: 9000
    protocol: TCP
  selector:
    app: kafdrop