apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: default
  labels:
    app: zookeeper
spec:
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: zookeeper
          image: "confluentinc/cp-zookeeper:6.2.1"
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_SERVER_ID
              value: "1"
            - name: ZOOKEEPER_SERVERS
              value: "zoo1:2888:3888"
---
apiVersion: v1
kind: Service
metadata:
  name: zoo1
  namespace: default
  labels:
    app: zookeeper
spec:
  type: ClusterIP
  ports:
  - name: client
    port: 2181
    protocol: TCP
  - name: follower
    port: 2888
    protocol: TCP
  - name: leader
    port: 3888
    protocol: TCP
  selector:
    app: zookeeper
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: default
  labels:
    app: kafka
spec:
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: kafka
          image: "confluentinc/cp-kafka:6.2.1"
          env:
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "INTERNAL://kafka1.default:19092,EXTERNAL://localhost:9092"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "INTERNAL"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zoo1:2181"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_LOG4J_LOGGERS
              value: kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO
---
apiVersion: v1
kind: Service
metadata:
  name: kafka1
  namespace: default
  labels:
    name: kafka
spec:
  ports:
  - port: 9092
    name: kafka-port-1
    protocol: TCP
  - port: 19092
    name: kafka-port-2
    protocol: TCP
  selector:
    app: kafka
  type: ClusterIP